version: '2'
services:
    nbmonline-app:
        image: nbmonline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nbmonline-mysql:3306/nbmonline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nbmonline-mysql:
        extends:
            file: mysql.yml
            service: nbmonline-mysql
